Repository laminas/laminas-cache, pull requests merged in 2021-07, with the labels that each got.

#126 bugfix: documentation reference to memory storage adapter
  README.md
  docs/book/installation.md
Labels: Bug

#127 bugfix: documentation reference to memory storage adapter
  README.md
  docs/book/installation.md
Labels: Bug, Documentation

#129 qa: force "stable" PHP version to 7.3 on 2.x branches
  .laminas-ci.json
Labels: Enhancement

#86 storage adapter factory backport to v2
  README.md
  composer.json
  docs/book/basic-usage.md
  docs/book/psr16.md
  docs/book/psr6.md
  docs/book/storage/adapter.md
  docs/book/storage/capabilities.md
  docs/book/storage/plugin.md
  src/ConfigProvider.php
  src/Service/StorageAdapterFactory.php
  src/Service/StorageAdapterFactoryFactory.php
  src/Service/StorageAdapterFactoryInterface.php
  src/Service/StoragePluginFactory.php
  src/Service/StoragePluginFactoryFactory.php
  src/Service/StoragePluginFactoryInterface.php
  src/StorageFactory.php
  test/Service/StorageAdapterFactoryFactoryTest.php
  test/Service/StorageAdapterFactoryTest.php
  test/Service/StoragePluginFactoryFactoryTest.php
  test/Service/StoragePluginFactoryTest.php
Labels: Documentation, Enhancement

#98 Deprecate `PatternOptions` `storage` option
  docs/book/pattern/callback-cache.md
  docs/book/pattern/capture-cache.md
  docs/book/pattern/class-cache.md
  docs/book/pattern/intro.md
  docs/book/pattern/object-cache.md
  docs/book/pattern/output-cache.md
  src/Pattern/AbstractPattern.php
  src/Pattern/AbstractStorageCapablePattern.php
  src/Pattern/CallbackCache.php
  src/Pattern/ClassCache.php
  src/Pattern/ObjectCache.php
  src/Pattern/OutputCache.php
  src/Pattern/PatternCacheFactory.php
  src/Pattern/PatternInterface.php
  src/Pattern/PatternOptions.php
  src/Pattern/StorageCapableInterface.php
  src/Pattern/StoragePatternCacheFactory.php
  src/PatternPluginManager/PatternPluginManagerTrait.php
  src/PatternPluginManager/PatternPluginManagerV2Polyfill.php
  src/PatternPluginManager/PatternPluginManagerV3Polyfill.php
  test/Pattern/AbstractCommonPatternTest.php
  test/Pattern/AbstractCommonStoragePatternTest.php
  test/Pattern/CallbackCacheTestAbstract.php
  test/Pattern/CaptureCacheTestAbstract.php
  test/Pattern/ClassCacheTestAbstract.php
  test/Pattern/ObjectCacheTestAbstract.php
  test/Pattern/OutputCacheTestAbstract.php
  test/Pattern/PatternCacheFactoryTest.php
  test/Pattern/StoragePatternCacheFactoryTest.php
  test/Pattern/TestAsset/TestCachePattern.php
  test/Pattern/TestAsset/TestClassCache.php
  test/PatternPluginManagerTest.php
Labels: Documentation, Enhancement

#118 qa: mark `ClassCache` pattern as deprecated
  composer.json
  docs/book/pattern/class-cache.md
  src/Pattern/ClassCache.php
Labels: Documentation, Enhancement

#132 docs: added array configuration schema
  docs/book/storage/adapter.md
Labels: Documentation

#131 Bugfix for deprecated configuration check with false positives
  src/Service/DeprecatedSchemaDetector.php
  test/Service/DeprecatedSchemaDetectorTest.php
Labels: Bug

#134 Bugfix: Expired cache items must not be queued for later persistence
  src/Psr/CacheItemPool/CacheItemPoolDecorator.php
  test/Psr/CacheItemPool/CacheItemPoolDecoratorTest.php
  test/Psr/CacheItemPool/TestAsset/FlushableStorageAdapterInterface.php
Labels: Bug

#135 Bugfix: Serializer should treat non-existent items as `0` when incrementing/decrementing items
  src/Storage/Plugin/Serializer.php
  test/Storage/Plugin/SerializerTest.php
Labels: Bug

#93 qa: remove `PatternFactory` as it was marked as deprecated in v2.11.0
  src/PatternFactory.php
  test/PatternFactoryTest.php
Labels: BC Break

#52 Remove deprecations from 2.x
  benchmark/AbstractCommonStorageAdapterBench.php
  benchmark/FilesystemStorageAdapterBench.php
  benchmark/MemoryStorageAdapterBench.php
  composer.json
  composer.lock
  docs/book/storage/capabilities.md
  psalm-baseline.xml
  psalm.xml
  src/ConfigProvider.php
  src/Pattern/AbstractStorageCapablePattern.php
  src/Pattern/CallbackCache.php
  src/Pattern/ClassCache.php
  src/Pattern/PatternCacheFactory.php
  src/Pattern/PatternInterface.php
  src/Pattern/PatternOptions.php
  src/Pattern/StoragePatternCacheFactory.php
  src/PatternPluginManager.php
  src/Psr/CacheItemPool/CacheItemPoolDecorator.php
  src/Service/PatternPluginManagerFactory.php
  src/Service/PluginManagerLookupTrait.php
  src/Service/StorageCacheAbstractServiceFactory.php
  src/Service/StorageCacheFactory.php
  src/Storage/Capabilities.php
  src/StorageFactory.php
  test/Pattern/AbstractCommonPatternTest.php
  test/Pattern/AbstractCommonStoragePatternTest.php
  test/Pattern/CallbackCacheTest.php
  test/Pattern/CaptureCacheTest.php
  test/Pattern/ClassCacheTest.php
  test/Pattern/ObjectCacheTest.php
  test/Pattern/OutputCacheTest.php
  test/Pattern/PatternCacheFactoryTest.php
  test/Pattern/StoragePatternCacheFactoryTest.php
  test/Pattern/TestAsset/TestCallbackCache.php
  test/Pattern/TestAsset/TestClassCache.php
  test/Pattern/TestAsset/TestObjectCache.php
  test/PatternPluginManagerTest.php
  test/Service/StorageCacheAbstractServiceFactoryTest.php
  test/Service/StorageCacheFactoryTest.php
  test/Storage/Adapter/AbstractAdapterTest.php
  test/Storage/Plugin/SerializerTest.php
  test/StorageFactoryTest.php
Labels: BC Break

#55 Remove all adapters from plugin manager
  src/Storage/AdapterPluginManager.php
Labels: BC Break, Enhancement

#142 Adds versioning for documentation
  docs/book/v2/basic-usage.md
  docs/book/v2/installation.md
  docs/book/v2/pattern/callback-cache.md
  docs/book/v2/pattern/capture-cache.md
  docs/book/v2/pattern/class-cache.md
  docs/book/v2/pattern/intro.md
  docs/book/v2/pattern/object-cache.md
  docs/book/v2/pattern/output-cache.md
  docs/book/v2/psr16.md
  docs/book/v2/psr6.md
  docs/book/v2/storage/adapter.md
  docs/book/v2/storage/capabilities.md
  docs/book/v2/storage/plugin.md
  docs/book/v3/installation.md
  docs/book/v3/pattern/callback-cache.md
  docs/book/v3/pattern/capture-cache.md
  docs/book/v3/pattern/intro.md
  docs/book/v3/pattern/object-cache.md
  docs/book/v3/pattern/output-cache.md
  docs/book/v3/psr16.md
  docs/book/v3/psr6.md
  docs/book/v3/storage/adapter.md
  docs/book/v3/storage/capabilities.md
  docs/book/v3/storage/plugin.md
  mkdocs.yml
Labels: Documentation, Enhancement

#141 Mark plugin managers final
  src/Service/StorageAdapterFactory.php
  src/Service/StoragePluginFactory.php
  src/Storage/AdapterPluginManager.php
  src/Storage/PluginManager.php
  test/Service/StorageAdapterFactoryFactoryTest.php
  test/Service/StorageAdapterFactoryTest.php
  test/Service/StoragePluginFactoryFactoryTest.php
  test/Service/StoragePluginFactoryTest.php
Labels: BC Break, Enhancement

#143 Remove dependency of cache adapters
  composer.json
  composer.lock
Labels: Enhancement

#144 Use dependency inversion for cache adapters
  composer.json
  composer.lock
Labels: Enhancement

#145 Documentation for APCu adapter
  README.md
  docs/book/v3/storage/adapter.md
Labels: Documentation, Enhancement
