Repository laminas/laminas-cache, pull requests merged in 2021-11, with the labels that each got.

#169 Widening return type hint of SimpleCacheDecorator::translateThrowable method
  src/Psr/SimpleCache/SimpleCacheDecorator.php
  test/Psr/SimpleCache/SimpleCacheDecoratorTest.php
Labels: Bug, hacktoberfest-accepted

#172 Pass `$options` in `StoragePluginFactory`
  src/Storage/PluginManager.php
  test/Service/StoragePluginFactoryIntegrationTest.php
Labels: Bug

#60 Migration Guide for v3.0
  docs/book/v3/reference/migration.md
Labels: Documentation

#177 PSR-6 maximum cache key length validation
  docs/book/v3/reference/migration.md
  psalm-baseline.xml
  src/Psr/CacheItemPool/CacheItemPoolDecorator.php
  src/Psr/CacheItemPool/InvalidArgumentException.php
  src/Psr/MaximumKeyLengthTrait.php
  src/Psr/SerializationTrait.php
  src/Psr/SimpleCache/SimpleCacheDecorator.php
  src/Psr/SimpleCache/SimpleCacheInvalidArgumentException.php
  test/Psr/CacheItemPool/CacheItemPoolDecoratorTest.php
  test/Psr/SimpleCache/SimpleCacheDecoratorTest.php
Labels: BC Break, Enhancement

#178 Documentation: remove superfluous word
  docs/book/v3/reference/migration.md
Labels: Bug, Documentation

#180 Adds missing migration guide to navigation
  docs/book/v3/migration/to-version-3.md
  mkdocs.yml
Labels: Bug, Documentation

#182 Allow `adapter` as configuration key when using `StoragePluginFactoryInterface`
  src/Service/StoragePluginFactory.php
  src/Service/StoragePluginFactoryInterface.php
  test/Service/StoragePluginFactoryTest.php
Labels: Bug, Enhancement

#185 Fix storage adapter factory assertion with adapter key
  src/Service/StorageAdapterFactory.php
  test/Service/StorageAdapterFactoryTest.php
Labels: Bug
