Repository laminas/laminas-cache, pull requests merged in 2024-05, with the labels that each got.

#296 Support for `laminas/laminas-servicemanager` v4
  composer.json
  composer.lock
  psalm-baseline.xml
  src/Pattern/PatternOptions.php
  src/Service/StoragePluginFactoryInterface.php
  src/Storage/Adapter/AbstractAdapter.php
  src/Storage/Adapter/AdapterOptions.php
  src/Storage/AdapterPluginManager.php
  src/Storage/Event.php
  src/Storage/ExceptionEvent.php
  src/Storage/Plugin/PluginOptions.php
  src/Storage/Plugin/Serializer.php
  src/Storage/Plugin/SerializerFactory.php
  src/Storage/PluginManager.php
  src/Storage/PostEvent.php
  test/Service/StoragePluginFactoryIntegrationTest.php
  test/Storage/Adapter/AbstractAdapterTest.php
  test/Storage/AdapterPluginManagerTest.php
  test/Storage/Plugin/SerializerTest.php
  test/Storage/PluginManagerTest.php
  test/Storage/TestAsset/MockPlugin.php
Labels: BC Break, Enhancement

#274 Documentation for v4.0.0 including migration guide
  README.md
  docs/book/v4/application-integration/usage-in-a-laminas-mvc-application.md
  docs/book/v4/installation.md
  docs/book/v4/migration/to-version-4.md
  docs/book/v4/pattern/callback-cache.md
  docs/book/v4/pattern/capture-cache.md
  docs/book/v4/pattern/intro.md
  docs/book/v4/pattern/object-cache.md
  docs/book/v4/pattern/output-cache.md
  docs/book/v4/psr16.md
  docs/book/v4/psr6.md
  docs/book/v4/storage/adapter.md
  docs/book/v4/storage/capabilities.md
  docs/book/v4/storage/plugin.md
  mkdocs.yml
  src/ConfigProvider.php
  src/Module.php
  src/Pattern/CaptureCache.php
  src/Pattern/ObjectCache.php
  src/Psr/SerializationTrait.php
  src/Storage/Plugin/OptimizeByFactor.php
Labels: Documentation

#302 Sets current version in MkDocs configuration file
  mkdocs.yml
Labels: Bug, Documentation
