Repository laminas/laminas-cache, pull requests merged in 2024-11, with the labels that each got.

#350 Fix docs linting issues
  docs/book/index.md
  docs/book/v2/storage/adapter.md
  docs/book/v2/storage/plugin.md
  docs/book/v3/application-integration/usage-in-a-laminas-mvc-application.md
  docs/book/v3/storage/adapter.md
  docs/book/v3/storage/plugin.md
  docs/book/v4/application-integration/usage-in-a-laminas-mvc-application.md
  docs/book/v4/migration/to-version-4.md
  docs/book/v4/storage/adapter.md
  docs/book/v4/storage/capabilities.md
  docs/book/v4/storage/plugin.md
Labels: Documentation, QA

#351 Upgrade PHPUnit to version 10.x
  .coveralls.yml
  .gitignore
  composer.json
  composer.lock
  phpunit.xml.dist
  psalm-baseline.xml
  test/Pattern/AbstractCommonPatternTestCase.php
  test/Pattern/AbstractCommonStoragePatternTestCase.php
  test/Pattern/CallbackCacheTest.php
  test/Pattern/CaptureCacheTest.php
  test/Pattern/ObjectCacheTest.php
  test/Pattern/OutputCacheTest.php
  test/Psr/CacheItemPool/CacheItemPoolDecoratorTest.php
  test/Psr/SimpleCache/SimpleCacheDecoratorTest.php
  test/Service/ConfigProviderIntegrationTest.php
  test/Service/StorageAdapterFactoryFactoryTest.php
  test/Service/StorageAdapterFactoryTest.php
  test/Service/StorageCacheFactoryTest.php
  test/Service/StoragePluginFactoryTest.php
  test/Storage/Adapter/AbstractAdapterTest.php
  test/Storage/Adapter/AbstractMetadataCapableAdapterTest.php
  test/Storage/AdapterPluginManagerTest.php
  test/Storage/Plugin/AbstractCommonPluginTestCase.php
  test/Storage/Plugin/ClearExpiredByFactorTest.php
  test/Storage/Plugin/ExceptionHandlerTest.php
  test/Storage/Plugin/IgnoreUserAbortTest.php
  test/Storage/Plugin/OptimizeByFactorTest.php
  test/Storage/Plugin/SerializerTest.php
Labels: Enhancement, Dependencies, QA

#345 Update to use PHP 8.1 syntax
  src/Pattern/ObjectCache.php
  src/Psr/CacheItemPool/CacheItem.php
  src/Service/StorageAdapterFactory.php
  src/Service/StoragePluginFactory.php
  test/Psr/SimpleCache/SimpleCacheDecoratorTest.php
Labels: Enhancement

#352 Add Support for PHP 8.4
  .laminas-ci.json
  composer.json
  composer.lock
Labels: Enhancement, Dependencies
